export const allPart = [
  { name: "body", total: 17 },
  { name: "eyes", total: 17 },
  { name: "noses", total: 1 },
  { name: "hair", total: 73 },
  { name: "mouths", total: 24 },
  { name: "eyebrows", total: 15 },
  { name: "hats", total: 28 },
  { name: "glasses", total: 17 },
  { name: "earrings", total: 32 },
  { name: "neckwear", total: 18 },
  { name: "clothingL1", total: 5 },
  { name: "clothingL2", total: 5 },
  { name: "clothingL3", total: 9 },
];
